# Generated by Django 4.0.8 on 2022-11-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SsAdmCasosH',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('f_alta', models.DateTimeField(blank=True, db_column='F_alta', null=True)),
                ('f_final', models.DateTimeField(blank=True, db_column='F_final', null=True)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=60, null=True)),
                ('usuario', models.CharField(blank=True, max_length=15, null=True)),
                ('gestor', models.CharField(blank=True, max_length=10, null=True)),
                ('tiempo', models.TimeField(blank=True, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('proceso', models.IntegerField(blank=True, null=True)),
                ('validacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SS_Adm_Casos_H',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SsAdmCasosL',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('u_docentry', models.IntegerField(blank=True, db_column='U_DocEntry', null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('tiempo', models.TimeField(blank=True, null=True)),
                ('texto1', models.CharField(blank=True, max_length=255, null=True)),
                ('texto2', models.CharField(blank=True, max_length=255, null=True)),
                ('texto3', models.CharField(blank=True, max_length=255, null=True)),
                ('adjunto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SS_Adm_Casos_L',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SsUser',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=15)),
                ('pasword', models.TextField()),
                ('usrname', models.CharField(db_column='UsrName', max_length=40)),
                ('usrinc', models.CharField(db_column='UsrInc', max_length=3)),
                ('privilegios', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('passwd_email', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('tipo', models.CharField(blank=True, max_length=4, null=True)),
                ('gestcial', models.CharField(blank=True, db_column='GestCial', max_length=1, null=True)),
                ('movil', models.CharField(blank=True, max_length=9, null=True)),
                ('terminal', models.CharField(blank=True, max_length=30, null=True)),
                ('f_baja', models.DateField(blank=True, db_column='F_Baja', null=True)),
                ('r_code', models.IntegerField(blank=True, db_column='R_Code', null=True)),
            ],
            options={
                'db_table': 'SS_USER',
                'managed': False,
            },
        ),
    ]
