# Generated by Django 4.0.8 on 2022-11-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssadmcasosl',
            options={'managed': False},
        ),
    ]
