from django.urls import path
from . import views

urlpatterns = [
    path('', views.main),
    #Authentication Functions URLs
    path('auth/login', views.login),
    path('auth/logout', views.logout),
    path('auth/reset-password/validate-email', views.validate_email),
    path('auth/reset-password/validate-reset-key', views.validate_reset_key),
    path('auth/reset-password/change-password', views.change_user_password),
    #Tickets Functions URLs
    path('tickets/get-tickets', views.get_tickets),
    path('tickets/get-ticket', views.get_ticket),
    path('tickets/get-ticket-msgs', views.get_tickets_msgs),
    path('tickets/get-tickets-count', views.get_tickets_count),
    path('tickets/get-pending-tickets-count', views.get_pending_tickets_count),
    path('tickets/get-date-range-tickets', views.get_tickets_date_range),
    path('tickets/create-ticket', views.create_ticket),
    path('tickets/get-categories', views.get_categories),
    path('tickets/get-managers', views.get_managers),
    path('tickets/get-users', views.get_users),
    path('tickets/update-tickets-position', views.update_tickets_position),
    path('tickets/create-ticket-msg', views.create_ticket_msg),
    path('tickets/change-ticket-viewed-state', views.change_ticket_viewed_state),
    path('tickets/close-ticket', views.close_ticket),
    path('tickets/open-ticket', views.open_ticket),
    path('tickets/change-ticket-manager', views.change_ticket_manager),
    path('tickets/change-ticket-user', views.change_ticket_user),
    path('tickets/change-ticket-priority', views.change_ticket_priority),
    path('tickets/change-ticket-category', views.change_ticket_category),
    path('tickets/change-ticket-validation', views.change_ticket_validation),
    path('tickets/get-manuals', views.get_manuals),
    path('tickets/get-manuals-categories', views.get_manuals_categories),
    path('tickets/upload-file', views.upload_file),
    path('tickets/upload-file-existing-ticket', views.upload_file_existing_ticket),
    path('tickets/download-file', views.download_file),
    path('tickets/download-manual', views.download_manual),
    #Users Functions URLs
    path('user/upload-img', views.upload_profile_img),
    path('user/download-img', views.download_profile_img),
    path('users/get-users', views.get_users_info),
    path('users/get-user-img-path', views.get_user_img_path),
    path('users/get-user-info', views.get_user_info),
    path('users/edit-user', views.edit_user),
    path('users/disable-user', views.disable_user),
    path('users/enable-user', views.enable_user),
    path('users/create-user', views.create_user),
    #PowerBi Functions URLs
    path('powerbi/get-categories', views.get_powerbi_categories),
    path('powerbi/get-all-categories', views.get_all_powerbi_categories),
    path('powerbi/get-category', views.get_powerbi_category),
    path('powerbi/get-all-newness-publications', views.get_pwbi_newness_publications),
    path('powerbi/create-publication', views.create_pwbi_publication),
    path('powerbi/delete-pwbi-publication', views.delete_pwbi_publication),
    path('powerbi/change-publication-newness-state', views.change_publication_newness_state),
    path('powerbi/get-publications-news', views.get_pwbi_publications_news),
    path('powerbi/get-publications-guides', views.get_pwbi_publications_guides),
    path('powerbi/get-publication', views.get_pwbi_publication),
    path('powerbi/start-user-statistic-info', views.start_user_statistic_info),
    path('powerbi/end-user-statistic-info', views.end_user_statistic_info)
]